name: CI
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-make
      - run: makers ci

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-make,cargo-tarpaulin
      - run: makers coverage-ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-lcov
          path: target/coverage/lcov.info
